apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  storageClassName: standard
