apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster-external-rw
  namespace: cnpg
spec:
  selector:
    cnpg.io/cluster: postgresql-cluster
    cnpg.io/podRole: instance
  ports:
    - name: postgres
      protocol: TCP
      nodePort: 30000
      port: 5432
      targetPort: 5432
  type: LoadBalancer