apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cnpg
data:
  username: YWRtaW4=
  password: YWRtaW4=
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
  namespace: cnpg
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
type: kubernetes.io/basic-auth